require_relative '../classes/music'
require_relative '../classes/genre'
require_relative '../classes/book'
require_relative '../classes/label'
require_relative '../classes/game'
require_relative '../classes/author'
